Use 64-bit Cocoa instead of 32-bit Carbon for macOS builds
transmission-remote-gui/transgui pull request #1224
Opened 2019-06-24 05:05 UTC by someperson

I was able to compile a functional version of Transmission Remote GUI for macOS that uses Cocoa instead of Carbon and is 64-bit instead of 32-bit, which I have released on my fork. This is rather experimental and not well-tested, but I thought it might be a good idea to create a pull request now in order to raise awareness. Here be dragons!

2019-06-24 10:23 UTC, leonsoft-kras commented on VERSION.txt
> +5.16.0-cocoa-alpha1
This file contains only the version number.

2019-06-24 10:44 UTC, leonsoft-kras requested changes
everything is fine, except the version.txt file

2019-06-24 17:02 UTC, TravisBuddy commented
## Travis tests have failed

Hey @someperson,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;jobs&#x2F;549838033">View build log</a>


<details>
  <summary>
    <strong>
     sh -c &#39;cd setup&#x2F;macosx &amp;&amp; .&#x2F;create_app_new.sh&#39;
    </strong>
  </summary>

```
++cat ../../VERSION.txt

+prog_ver=5.16.0

++git rev-list --abbrev-commit --max-count=1 HEAD ../..

+build=6cc0bd6

++lazbuild -v

+lazarus_ver=2.0.2

++fpc -i V

++head -n 1

+fpc_ver='Free Pascal Compiler version 3.0.4'

+exename=../../transgui

+appname='Transmission Remote GUI'

+dmgfolder=./Release

+appfolder='./Release/Transmission Remote GUI.app'

+lazdir=/Developer/lazarus/

+'[' -z true ']'

+'[' '!' /Developer/lazarus/ = '' ']'

+lazdir=LAZARUS_DIR=/Developer/lazarus/

+sed -i.bak 's/'\''Version %s'\''/'\''Version %s Build 6cc0bd6'\''#13#10'\''Compiled by: Free Pascal Compiler version 3.0.4, Lazarus v2.0.2'\''/' ../../about.lfm

+lazbuild -B ../../transgui.lpi --lazarusdir=/Developer/lazarus/

Hint: (lazarus) Compiler custom params changed for FCL 1.0.1

  Old="-MObjFPC -Scghi -O1 -g -gl fcllaz.pas"

  Now="-MObjFPC -Scghi -O1 -gw -gl fcllaz.pas"

  State file="/Developer/lazarus/packager/units/i386-darwin/FCL.compiled"

Hint: (lazarus) Missing state file of trcomp 1.0: /Users/travis/build/transmission-remote-gui/transgui/lib/i386-darwin/trcomp.compiled

Info: (lazarus) Execute Title="Compile package FCL 1.0.1"

Info: (lazarus) Working Directory="/Developer/lazarus/packager/registration/"

Info: (lazarus) Executable="/usr/local/bin/ppc386"

Info: (lazarus) Param[0]="-B"

Info: (lazarus) Param[1]="-MObjFPC"

Info: (lazarus) Param[2]="-Scghi"

Info: (lazarus) Param[3]="-O1"

Info: (lazarus) Param[4]="-gw"

Info: (lazarus) Param[5]="-gl"

Info: (lazarus) Param[6]="-l"

Info: (lazarus) Param[7]="-vewnhibq"

Info: (lazarus) Param[8]="-Fu/Developer/lazarus/packager/registration/"

Info: (lazarus) Param[9]="-FU/Developer/lazarus/packager/units/i386-darwin/"

Info: (lazarus) Param[10]="fcllaz.pas"

Hint: (11030) Start of reading config file /etc/fpc.cfg

Hint: (11031) End of reading config file /etc/fpc.cfg

Free Pascal Compiler version 3.0.4 [2017/11/26] for i386

Copyright (c) 1993-2017 by Florian Klaempfl and others

(1002) Target OS: Darwin for i386

(3104) Compiling fcllaz.pas

(3104) Compiling lazaruspackageintf.pas

(9001) Assembling (pipe) /Developer/lazarus/packager/units/i386-darwin/lazaruspackageintf.s

(9001) Assembling (pipe) /Developer/lazarus/packager/units/i386-darwin/fcllaz.s

(1008) 124 lines compiled, 0.2 sec

(1022) 2 hint(s) issued

Info: (lazarus) Execute Title="Compile package LazUtils 1.0"

Info: (lazarus) Working Directory="/Developer/lazarus/components/lazutils/"

Info: (lazarus) Executable="/usr/local/bin/ppc386"

Info: (lazarus) Param[0]="-B"

Info: (lazarus) Param[1]="-MObjFPC"

Info: (lazarus) Param[2]="-Scghi"

Info: (lazarus) Param[3]="-O1"

Info: (lazarus) Param[4]="-gw"

Info: (lazarus) Param[5]="-gl"

Info: (lazarus) Param[6]="-l"

Info: (lazarus) Param[7]="-vewnhibq"

Info: (lazarus) Param[8]="-Fu/Developer/lazarus/packager/units/i386-darwin"

Info: (lazarus) Param[9]="-Fu/Developer/lazarus/components/lazutils/"

Info: (lazarus) Param[10]="-FU/Developer/lazarus/components/lazutils/lib/i386-darwin/"

Info: (lazarus) Param[11]="lazutils.pas"

Hint: (11030) Start of reading config file /etc/fpc.cfg

Hint: (11031) End of reading config file /etc/fpc.cfg

Free Pascal Compiler version 3.0.4 [2017/11/26] for i386

Copyright (c) 1993-2017 by Florian Klaempfl and others

(1002) Target OS: Darwin for i386

(3104) Compiling lazutils.pas

(3104) Compiling avglvltree.pas

(3104) Compiling laz_avl_tree.pp

/Developer/lazarus/components/lazutils/laz_avl_tree.pp(95,33) Hint: (5024) Parameter "aNode" not used

/Developer/lazarus/components/lazutils/laz_avl_tree.pp(98,30) Hint: (5024) Parameter "aNode" not used

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/laz_avl_tree.s

(3104) Compiling lazfileutils.pas

(3104) Compiling lazutf8.pas

(3104) Compiling fpcadds.pas

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/fpcadds.s

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazutf8.s

(3104) Compiling lazutilsstrconsts.pas

(1010) Writing Resource String Table file: lazutilsstrconsts.rsj

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazutilsstrconsts.s

/Developer/lazarus/components/lazutils/lazfileutils.inc(455,24) Warning: (5044) Symbol "faSysFile" is not portable

/Developer/lazarus/components/lazutils/lazfileutils.inc(457,23) Warning: (5044) Symbol "faHidden" is not portable

/Developer/lazarus/components/lazutils/lazfileutils.inc(458,25) Warning: (5043) Symbol "faVolumeId" is deprecated

/Developer/lazarus/components/lazutils/lazfileutils.inc(458,25) Warning: (5044) Symbol "faVolumeId" is not portable

/Developer/lazarus/components/lazutils/lazfileutils.inc(459,24) Warning: (5044) Symbol "faSymLink" is not portable

/Developer/lazarus/components/lazutils/unixlazfileutils.inc(67,45) Hint: (5057) Local variable "st" does not seem to be initialized

/Developer/lazarus/components/lazutils/unixlazfileutils.inc(256,39) Hint: (5057) Local variable "Info" does not seem to be initialized

/Developer/lazarus/components/lazutils/unixlazfileutils.inc(339,32) Hint: (5057) Local variable "FileInfo" does not seem to be initialized

/Developer/lazarus/components/lazutils/lazfileutils.pas(157,31) Hint: (5024) Parameter "Path" not used

/Developer/lazarus/components/lazutils/lazfileutils.pas(158,38) Hint: (5024) Parameter "Path" not used

/Developer/lazarus/components/lazutils/unixlazfileutils.inc(378,37) Hint: (5057) Local variable "info" does not seem to be initialized

/Developer/lazarus/components/lazutils/lazfileutils.pas(372,44) Hint: (5057) Local variable "StrSize" does not seem to be initialized

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazfileutils.s

(3104) Compiling lazdbglog.pas

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazdbglog.s

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/avglvltree.s

(3104) Compiling dynamicarray.pas

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/dynamicarray.s

(3104) Compiling dynhasharray.pp

(3104) Compiling lazloggerbase.pas

(3104) Compiling lazclasses.pas

(3104) Compiling lazmethodlist.pas

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazmethodlist.s

(9001) Assembling (pipe) /Developer/lazarus/components/lazutils/lib/i386-darwin/lazclasses.s

/Developer/lazarus/components/lazutils/LazLoggerImpl.inc(335,23) Hint: (4055) Conversion between ordinals and pointers is not portable

/Developer/lazarus/components/lazutils/lazloggerbase.pas(122,36) Hint: (5024) Parameter "AIndex" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(126,41) Hint: (5024) Parameter "s" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(119,35) Hint: (5024) Parameter "LogGroup" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(120,35) Hint: (5024) Parameter "LogGroup" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(124,35) Hint: (5024) Parameter "s" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(125,36) Hint: (5024) Parameter "s" not used

/Developer/lazarus/components/lazutils/lazloggerbase.pas(766,36) Warning: (4104) Implicit string type conversion from "AnsiString" to "WideString"

/Developer/lazarus/components/lazutils/lazloggerbase.pas(766,48) Warning: (4105) Implicit string type conversion with potential data loss from "WideString" to "AnsiString"

/Developer/la [...]

2019-06-24 17:30 UTC, someperson commented on VERSION.txt
> +5.16.0-cocoa-alpha1
I went ahead an reverted this change.

2019-06-25 14:18 UTC, leonsoft-kras submitted a review, later dismissed

2019-06-29 11:46 UTC, bertybassett commented
on a fresh install of 10.15 public beta I get

```
Process:               transgui [1374]
Path:                  /Applications/Transmission Remote GUI.app/Contents/MacOS/transgui
Identifier:            com.transgui
Version:               Transmission Remote GUI 5.16.0-cocoa-alpha1 (5.16.0-cocoa-alpha1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           transgui [1374]
User ID:               501

Date/Time:             2019-06-29 12:44:42.822 +0100
OS Version:            Mac OS X 10.15 (19A487m)
Report Version:        12
Anonymous UUID:        FC915F11-8F6B-48F7-F85C-6E6CFDC5D4D3


Time Awake Since Boot: 8600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot update for observer <NSFrontmostDocumentWindowObserver 0x7fff8eae6b88> for the key path "mainWindow.representedURL" from <TCocoaApplication 0x101e02fb0>, most likely because the value for the key "mainWindow" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the TCocoaApplication class.'
abort() called
terminating with uncaught exception of type NSException
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
Invalid dylib load. Clients should not load the unversioned libssl dylib as it does not have a stable ABI.

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff331c5063 __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff6894606b objc_exception_throw + 48
2   Foundation                          0x00007fff35855912 -[NSKeyValueNestedProperty object:withObservance:didChangeValueForKeyOrKeys:recurse:forwardingValues:] + 778
3   Foundation                          0x00007fff35952ae3 NSKeyValueDidChange.llvm.7740785217592564639 + 183
4   Foundation                          0x00007fff35952421 NSKeyValueDidChangeWithPerThreadPendingNotifications.llvm.7740785217592564639 + 146
5   AppKit                              0x00007fff3062f559 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 452
6   AppKit                              0x00007fff3062f38f -[NSApplication beginModalSessionForWindow:] + 37
7   transgui                            0x00000001001501fa transgui + 1376762
8   transgui                            0x000000010016381d transgui + 1456157
9   transgui                            0x0000000100021548 transgui + 136520
10  transgui                            0x0000000100046335 transgui + 287541
11  transgui                            0x00000001001b2d15 transgui + 1781013
12  transgui                            0x000000010004289e transgui + 272542
13  transgui                            0x00000001001bcc1d transgui + 1821725
14  transgui                            0x000000010014785c transgui + 1341532
15  Foundation                          0x00007fff3581545c __NSFireTimer + 67
16  CoreFoundation                      0x00007fff33133008 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
17  CoreFoundation                      0x00007fff33132bc2 __CFRunLoopDoTimer + 859
18  CoreFoundation                      0x00007fff331325e8 __CFRunLoopDoTimers + 317
19  CoreFoundation                      0x00007fff3311372b __CFRunLoopRun + 2213
20  CoreFoundation                      0x00007fff33112c01 CFRunLoopRunSpecific + 499
21  HIToolbox                           0x00007fff31d4953d RunCurrentEventLoopInMode + 292
22  HIToolbox                           0x00007fff31d4927d ReceiveNextEventCommon + 600
23  HIToolbox                           0x00007fff31d49007 _BlockUntilNextEventMatchingListInModeWithFilter + 64
24  AppKit                              0x00007fff3041b804 _DPSNextEvent + 990
25  AppKit                              0x00007fff3041a577 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
26  transgui                            0x000000010014618c transgui + 1335692
27  transgui                            0x00000001001466eb transgui + 1337067
28  transgui                            0x0000000100025aba transgui + 154298
29  transgui                            0x00000001000279e8 transgui + 162280
30  transgui                            0x0000000100027ec4 transgui + 163524
31  transgui                            0x0000000100145c8f transgui + 1334415
32  transgui                            0x000000010014651a transgui + 1336602
33  transgui                            0x0000000100027e70 transgui + 163440
34  transgui                            0x000000010000114d transgui + 4429
35  ???                                 0x0000000000000001 0x0 + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff69e1e5be __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff69edb738 pthread_kill + 203
2   libsystem_c.dylib             	0x00007fff69da6a5c abort + 120
3   libc++abi.dylib               	0x00007fff66e7abc8 abort_message + 231
4   libc++abi.dylib               	0x00007fff66e7ad7c demangling_terminate_handler() + 262
5   libobjc.A.dylib               	0x00007fff68947f4e _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff66e87da7 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff66e79fbe __cxa_rethrow + 99
8   libobjc.A.dylib               	0x00007fff689463e9 objc_exception_rethrow + 37
9   com.apple.Foundation          	0x00007fff35855958 -[NSKeyValueNestedProperty object:withObservance:didChangeValueForKeyOrKeys:recurse:forwardingValues:] + 848
10  com.apple.Foundation          	0x00007fff35952ae3 NSKeyValueDidChange.llvm.7740785217592564639 + 183
11  com.apple.Foundation          	0x00007fff35952421 NSKeyValueDidChangeWithPerThreadPendingNotifications.llvm.7740785217592564639 + 146
12  com.apple.AppKit              	0x00007fff3062f559 -[NSApplication _commonBeginModalSessionForWindow:relativeToWindow:modalDelegate:didEndSelector:contextInfo:] + 452
13  com.apple.AppKit              	0x00007fff3062f38f -[NSApplication beginModalSessionForWindow:] + 37
14  com.transgui                  	0x00000001001501fa 0x100000000 + 1376762
15  com.transgui                  	0x000000010016381d 0x100000000 + 1456157
16  com.transgui                  	0x0000000100021548 0x100000000 + 136520
17  com.transgui                  	0x0000000100046335 0x100000000 + 287541
18  com.transgui                  	0x00000001001b2d15 0x100000000 + 1781013
19  com.transgui                  	0x000000010004289e 0x100000000 + 272542
20  com.transgui                  	0x00000001001bcc1d 0x100000000 + 1821725
21  com.transgui                  	0x000000010014785c 0x100000000 + 1341532
22  com.apple.Foundation          	0x00007fff3581545c __NSFireTimer + 67
23  com.apple.CoreFoundation      	0x00007fff33133008 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
24  com.apple.CoreFoundation      	0x00007fff33132bc2 __CFRunLoopDoTimer + 859
25  com.apple.CoreFoundation      	0x00007fff331325e8 __CFRunLoopDoTimers + 317
26  com.apple.CoreFoundation      	0x00007fff3311372b __CFRunLoopRun + 2213
27  com.apple.CoreFoundation      	0x00007fff33112c01 CFRunLoopRunSpecific + 499
28  com.apple.HIToolbox           	0x00007fff31d4953d RunCurrentEventLoopInMode + 292
29  com.apple.HIToolbox           	0x00007fff31d4927d ReceiveNextEventCommon + 600
30  com.apple.HIToolbox           	0x00007fff31d49007 _BlockUntilNextEventMatchingListInModeWithFilter + 64
31  com.apple.AppKit              	0x00007fff3041b804 _DPSNextEvent + 990
32  com.apple.AppKit              	0x00007fff3041a577 -[NSApplication(NSEvent) _nextEve [...]

2019-06-30 01:23 UTC, someperson commented
> ```
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Cannot update for observer <NSFrontmostDocumentWindowObserver 0x7fff8eae6b88> for the key path "mainWindow.representedURL" from <TCocoaApplication 0x101e02fb0>, most likely because the value for the key "mainWindow" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the TCocoaApplication class.'
> ```

This appears to be caused by a known issue in Lazarus that will be fixed in the next version. See https://bugs.freepascal.org/view.php?id=35702

I think our best bet here will be to just wait for the next version before supporting 10.15. The application could be built using an SVN pull of Lazarus to work around this, but that would add a fair amount of complexity to the build process and I don't know what sort of issues it could potentially cause. I think it's also worth noting that 10.15 is still in the prerelease stage, so supporting it at this stage probably isn't critical.

2019-06-30 06:57 UTC, PeterDaveHello commented
@someperson thanks again, I agree with you about just wait for the next version, and I also need more time to test it!

cc #1150

2019-06-30 06:59 UTC, PeterDaveHello commented on VERSION.txt
> +5.16.0-cocoa-alpha1
@someperson would you like to squash the revert commit into where it originally happened or just squash all the commits into single one? I'll be better for code tracing and commit history, thanks.

2019-06-30 19:29 UTC, someperson commented on VERSION.txt
> +5.16.0-cocoa-alpha1
> @someperson would you like to squash the revert commit into where it originally happened or just squash all the commits into single one? I'll be better for code tracing and commit history, thanks.

No problem. I just squashed the commits as requested.

2019-06-30 19:38 UTC, TravisBuddy commented
## Travis tests have failed

Hey @someperson,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;jobs&#x2F;552486986">View build log</a>


<details>
  <summary>
    <strong>
     docker run -e DEBIAN_FRONTEND&#x3D;noninteractive -it --rm -v &quot;${PWD}:&#x2F;transgui&quot; -v &#x2F;usr&#x2F;bin&#x2F;qemu-arm-static:&#x2F;usr&#x2F;bin&#x2F;qemu-arm-static resin&#x2F;rpi-raspbian:stretch bash -c &quot;sed -i &#39;s&#x2F;archive.raspbian.org&#x2F;mirrors.ocf.berkeley.edu\&#x2F;raspbian&#x2F;g&#39; &#x2F;etc&#x2F;apt&#x2F;sources.list &amp;&amp; cd &#x2F;transgui&#x2F;setup&#x2F;unix&#x2F; &amp;&amp; .&#x2F;debian-ubuntu-install_deps.sh &amp;&amp; apt upgrade -y &amp;&amp; .&#x2F;build.sh&quot;
    </strong>
  </summary>

```
Unable to find image 'resin/rpi-raspbian:stretch' locally
stretch: Pulling from resin/rpi-raspbian












Digest: sha256:e4938fd283abc60021efa24f8ebbde9d3b0135849dd1297093b06a18578963b4
Status: Downloaded newer image for resin/rpi-raspbian:stretch
[WARN  tini (26)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
+ apt update -yqq
26 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ apt install -yqq lazarus xz-utils coreutils git make jq zip libssl-dev
coreutils is already the newest version (8.26-3).
xz-utils is already the newest version (5.2.2-1.2).
The following additional packages will be installed:
  binutils dh-python fontconfig fontconfig-config fonts-dejavu-core
  fp-compiler fp-compiler-3.0.0 fp-units-base fp-units-base-3.0.0 fp-units-fcl
  fp-units-fcl-3.0.0 fp-units-gtk2 fp-units-gtk2-3.0.0 fp-units-rtl-3.0.0
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0
  gir1.2-gtk-2.0 gir1.2-pango-1.0 git-man gnome-icon-theme
  gtk-update-icon-cache hicolor-icon-theme icu-devtools lazarus-1.6
  lazarus-doc-1.6 lazarus-ide lazarus-ide-1.6 lazarus-ide-gtk2-1.6
  lazarus-src-1.6 lcl-1.6 lcl-gtk2-1.6 lcl-nogui-1.6 lcl-units-1.6
  lcl-utils-1.6 libasan3 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libc-dev-bin
  libc6 libc6-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcairo2-dev libcroco3 libcups2 libcurl3-gnutls libdatrie1 libdpkg-perl
  libelf1 liberror-perl libexpat1 libexpat1-dev libfontconfig1
  libfontconfig1-dev libfreetype6 libfreetype6-dev libgcc-6-dev libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev libgomp1 libgraphite2-3 libgraphite2-dev libgtk2.0-0
  libgtk2.0-common libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
  libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libicu57
  libjbig0 libjpeg62-turbo libjq1 liblzo2-2 libmpdec2 libonig4 libpango-1.0-0
  libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.24 libpixman-1-0
  libpixman-1-dev libpng-dev libpng16-16 libpthread-stubs0-dev
  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib librsvg2-2
  librsvg2-common libsm-dev libsm6 libstdc++-6-dev libthai-data libthai0
  libtiff5 libubsan0 libx11-6 libx11-data libx11-dev libxau-dev libxau6
  libxcb-render0 libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1
  libxcb1-dev libxcomposite-dev libxcomposite1 libxcursor-dev libxcursor1
  libxdamage-dev libxdamage1 libxdmcp-dev libxdmcp6 libxext-dev libxext6
  libxfixes-dev libxfixes3 libxft-dev libxft2 libxi-dev libxi6 libxinerama-dev
  libxinerama1 libxml2 libxml2-utils libxrandr-dev libxrandr2 libxrender-dev
  libxrender1 linux-libc-dev mime-support perl perl-modules-5.24 pkg-config
  python3 python3-minimal python3.5 python3.5-minimal shared-mime-info ucf
  x11-common x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
  x11proto-render-dev x11proto-xext-dev x11proto-xinerama-dev
  xorg-sgml-doctools xtrans-dev zlib1g-dev
Suggested packages:
  binutils-doc fp-docs-3.0.0 mingw32-binutils uuid-dev gettext-base
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-arch git-cvs git-mediawiki git-svn fp-docs fp-utils gdb glibc-doc
  libc-l10n locales manpages-dev libcairo2-doc cups-common debian-keyring gcc
  | c-compiler patch libglib2.0-doc gvfs libgtk2.0-doc libice-doc icu-doc
  imagemagick libpango1.0-doc librsvg2-bin libsm-doc libstdc++-6-doc
  libxcb-doc libxext-doc make-doc perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl python3-doc python3-tk python3-venv
  python3.5-venv python3.5-doc binfmt-support
Recommended packages:
  fp-utils-3.0.0 patch less rsync ssh-client fpc fpc-source gdb manpages
  manpages-dev libfile-fcntllock-perl bzip2 xdg-user-dirs libgail-common
  libgtk2.0-bin python debhelper libpng-tools libssl-doc libx11-doc xml-core
  file rename unzip
The following NEW packages will be installed:
  binutils dh-python fontconfig fontconfig-config fonts-dejavu-core
  fp-compiler fp-compiler-3.0.0 fp-units-base fp-units-base-3.0.0 fp-units-fcl
  fp-units-fcl-3.0.0 fp-units-gtk2 fp-units-gtk2-3.0.0 fp-units-rtl-3.0.0
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0
  gir1.2-gtk-2.0 gir1.2-pango-1.0 git git-man gnome-icon-theme
  gtk-update-icon-cache hicolor-icon-theme icu-devtools jq lazarus lazarus-1.6
  lazarus-doc-1.6 lazarus-ide lazarus-ide-1.6 lazarus-ide-gtk2-1.6
  lazarus-src-1.6 lcl-1.6 lcl-gtk2-1.6 lcl-nogui-1.6 lcl-units-1.6
  lcl-utils-1.6 libasan3 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libc-dev-bin
  libc6-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcairo2-dev libcroco3 libcups2 libcurl3-gnutls libdatrie1 libdpkg-perl
  libelf1 liberror-perl libexpat1 libexpat1-dev libfontconfig1
  libfontconfig1-dev libfreetype6 libfreetype6-dev libgcc-6-dev libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev libgomp1 libgraphite2-3 libgraphite2-dev libgtk2.0-0
  libgtk2.0-common libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
  libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libicu57
  libjbig0 libjpeg62-turbo libjq1 liblzo2-2 libmpdec2 libonig4 libpango-1.0-0
  libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.24 libpixman-1-0
  libpixman-1-dev libpng-dev libpthread-stubs0-dev libpython3-stdlib
  libpython3.5-minimal libpython3.5-stdlib librsvg2-2 librsvg2-common
  libsm-dev libsm6 libssl-dev libstdc++-6-dev libthai-data libthai0 libtiff5
  libubsan0 libx11-6 libx11-data libx11-dev libxau-dev libxau6 libxcb-render0
  libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1 libxcb1-dev
  libxcomposite-dev libxcomposite1 libxcursor-dev libxcursor1 libxdamage-dev
  libxdamage1 libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxfixes-dev
  libxfixes3 libxft-dev libxft2 libxi-dev libxi6 libxinerama-dev libxinerama1
  libxml2 libxml2-utils libxrandr-dev libxrandr2 libxrender-dev libxrender1
  linux-libc-dev make mime-support perl perl-modules-5.24 pkg-config python3
  python3-minimal python3.5 python3.5-minimal shared-mime-info ucf x11-common
  x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
  x11proto-render-dev x11proto-xext-dev x11proto-xinerama [...]

2019-06-30 19:57 UTC, PeterDaveHello commented
no mind, just triggered the build again, those for raspberry pi fails frequently on Travis CI

2019-06-30 20:06 UTC, TravisBuddy commented
## Travis tests have failed

Hey @someperson,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;jobs&#x2F;552486986">View build log</a>


<details>
  <summary>
    <strong>
     docker run -e DEBIAN_FRONTEND&#x3D;noninteractive -it --rm -v &quot;${PWD}:&#x2F;transgui&quot; -v &#x2F;usr&#x2F;bin&#x2F;qemu-arm-static:&#x2F;usr&#x2F;bin&#x2F;qemu-arm-static resin&#x2F;rpi-raspbian:stretch bash -c &quot;sed -i &#39;s&#x2F;archive.raspbian.org&#x2F;mirrors.ocf.berkeley.edu\&#x2F;raspbian&#x2F;g&#39; &#x2F;etc&#x2F;apt&#x2F;sources.list &amp;&amp; cd &#x2F;transgui&#x2F;setup&#x2F;unix&#x2F; &amp;&amp; .&#x2F;debian-ubuntu-install_deps.sh &amp;&amp; apt upgrade -y &amp;&amp; .&#x2F;build.sh&quot;
    </strong>
  </summary>

```
Unable to find image 'resin/rpi-raspbian:stretch' locally
stretch: Pulling from resin/rpi-raspbian












Digest: sha256:e4938fd283abc60021efa24f8ebbde9d3b0135849dd1297093b06a18578963b4
Status: Downloaded newer image for resin/rpi-raspbian:stretch
[WARN  tini (26)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
+ apt update -yqq
26 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ apt install -yqq lazarus xz-utils coreutils git make jq zip libssl-dev
coreutils is already the newest version (8.26-3).
xz-utils is already the newest version (5.2.2-1.2).
The following additional packages will be installed:
  binutils dh-python fontconfig fontconfig-config fonts-dejavu-core
  fp-compiler fp-compiler-3.0.0 fp-units-base fp-units-base-3.0.0 fp-units-fcl
  fp-units-fcl-3.0.0 fp-units-gtk2 fp-units-gtk2-3.0.0 fp-units-rtl-3.0.0
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0
  gir1.2-gtk-2.0 gir1.2-pango-1.0 git-man gnome-icon-theme
  gtk-update-icon-cache hicolor-icon-theme icu-devtools lazarus-1.6
  lazarus-doc-1.6 lazarus-ide lazarus-ide-1.6 lazarus-ide-gtk2-1.6
  lazarus-src-1.6 lcl-1.6 lcl-gtk2-1.6 lcl-nogui-1.6 lcl-units-1.6
  lcl-utils-1.6 libasan3 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libc-dev-bin
  libc6 libc6-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcairo2-dev libcroco3 libcups2 libcurl3-gnutls libdatrie1 libdpkg-perl
  libelf1 liberror-perl libexpat1 libexpat1-dev libfontconfig1
  libfontconfig1-dev libfreetype6 libfreetype6-dev libgcc-6-dev libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev libgomp1 libgraphite2-3 libgraphite2-dev libgtk2.0-0
  libgtk2.0-common libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
  libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libicu57
  libjbig0 libjpeg62-turbo libjq1 liblzo2-2 libmpdec2 libonig4 libpango-1.0-0
  libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.24 libpixman-1-0
  libpixman-1-dev libpng-dev libpng16-16 libpthread-stubs0-dev
  libpython3-stdlib libpython3.5-minimal libpython3.5-stdlib librsvg2-2
  librsvg2-common libsm-dev libsm6 libstdc++-6-dev libthai-data libthai0
  libtiff5 libubsan0 libx11-6 libx11-data libx11-dev libxau-dev libxau6
  libxcb-render0 libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1
  libxcb1-dev libxcomposite-dev libxcomposite1 libxcursor-dev libxcursor1
  libxdamage-dev libxdamage1 libxdmcp-dev libxdmcp6 libxext-dev libxext6
  libxfixes-dev libxfixes3 libxft-dev libxft2 libxi-dev libxi6 libxinerama-dev
  libxinerama1 libxml2 libxml2-utils libxrandr-dev libxrandr2 libxrender-dev
  libxrender1 linux-libc-dev mime-support perl perl-modules-5.24 pkg-config
  python3 python3-minimal python3.5 python3.5-minimal shared-mime-info ucf
  x11-common x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
  x11proto-render-dev x11proto-xext-dev x11proto-xinerama-dev
  xorg-sgml-doctools xtrans-dev zlib1g-dev
Suggested packages:
  binutils-doc fp-docs-3.0.0 mingw32-binutils uuid-dev gettext-base
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-arch git-cvs git-mediawiki git-svn fp-docs fp-utils gdb glibc-doc
  libc-l10n locales manpages-dev libcairo2-doc cups-common debian-keyring gcc
  | c-compiler patch libglib2.0-doc gvfs libgtk2.0-doc libice-doc icu-doc
  imagemagick libpango1.0-doc librsvg2-bin libsm-doc libstdc++-6-doc
  libxcb-doc libxext-doc make-doc perl-doc libterm-readline-gnu-perl
  | libterm-readline-perl-perl python3-doc python3-tk python3-venv
  python3.5-venv python3.5-doc binfmt-support
Recommended packages:
  fp-utils-3.0.0 patch less rsync ssh-client fpc fpc-source gdb manpages
  manpages-dev libfile-fcntllock-perl bzip2 xdg-user-dirs libgail-common
  libgtk2.0-bin python debhelper libpng-tools libssl-doc libx11-doc xml-core
  file rename unzip
The following NEW packages will be installed:
  binutils dh-python fontconfig fontconfig-config fonts-dejavu-core
  fp-compiler fp-compiler-3.0.0 fp-units-base fp-units-base-3.0.0 fp-units-fcl
  fp-units-fcl-3.0.0 fp-units-gtk2 fp-units-gtk2-3.0.0 fp-units-rtl-3.0.0
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0
  gir1.2-gtk-2.0 gir1.2-pango-1.0 git git-man gnome-icon-theme
  gtk-update-icon-cache hicolor-icon-theme icu-devtools jq lazarus lazarus-1.6
  lazarus-doc-1.6 lazarus-ide lazarus-ide-1.6 lazarus-ide-gtk2-1.6
  lazarus-src-1.6 lcl-1.6 lcl-gtk2-1.6 lcl-nogui-1.6 lcl-units-1.6
  lcl-utils-1.6 libasan3 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libc-dev-bin
  libc6-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcairo2-dev libcroco3 libcups2 libcurl3-gnutls libdatrie1 libdpkg-perl
  libelf1 liberror-perl libexpat1 libexpat1-dev libfontconfig1
  libfontconfig1-dev libfreetype6 libfreetype6-dev libgcc-6-dev libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev libgomp1 libgraphite2-3 libgraphite2-dev libgtk2.0-0
  libgtk2.0-common libgtk2.0-dev libharfbuzz-dev libharfbuzz-gobject0
  libharfbuzz-icu0 libharfbuzz0b libice-dev libice6 libicu-dev libicu57
  libjbig0 libjpeg62-turbo libjq1 liblzo2-2 libmpdec2 libonig4 libpango-1.0-0
  libpango1.0-dev libpangocairo-1.0-0 libpangoft2-1.0-0 libpangoxft-1.0-0
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.24 libpixman-1-0
  libpixman-1-dev libpng-dev libpthread-stubs0-dev libpython3-stdlib
  libpython3.5-minimal libpython3.5-stdlib librsvg2-2 librsvg2-common
  libsm-dev libsm6 libssl-dev libstdc++-6-dev libthai-data libthai0 libtiff5
  libubsan0 libx11-6 libx11-data libx11-dev libxau-dev libxau6 libxcb-render0
  libxcb-render0-dev libxcb-shm0 libxcb-shm0-dev libxcb1 libxcb1-dev
  libxcomposite-dev libxcomposite1 libxcursor-dev libxcursor1 libxdamage-dev
  libxdamage1 libxdmcp-dev libxdmcp6 libxext-dev libxext6 libxfixes-dev
  libxfixes3 libxft-dev libxft2 libxi-dev libxi6 libxinerama-dev libxinerama1
  libxml2 libxml2-utils libxrandr-dev libxrandr2 libxrender-dev libxrender1
  linux-libc-dev make mime-support perl perl-modules-5.24 pkg-config python3
  python3-minimal python3.5 python3.5-minimal shared-mime-info ucf x11-common
  x11proto-composite-dev x11proto-core-dev x11proto-damage-dev
  x11proto-fixes-dev x11proto-input-dev x11proto-kb-dev x11proto-randr-dev
  x11proto-render-dev x11proto-xext-dev x11proto-xinerama [...]

2019-07-13 21:33 UTC, TravisBuddy commented
Hey @someperson,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;builds&#x2F;558358787">View build log</a>

###### TravisBuddy Request Identifier: e24cfa30-a5b5-11e9-95e8-170b8b084361

2019-07-13 21:51 UTC, TravisBuddy commented
Hey @someperson,
Something went wrong with the build.

TravisCI finished with status `errored`, which means the build failed because of something unrelated to the tests, such as a problem with a dependency or the build process itself.

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;builds&#x2F;558360003">View build log</a>

###### TravisBuddy Request Identifier: 4e9cdfa0-a5b8-11e9-95e8-170b8b084361

2019-07-13 23:40 UTC, TravisBuddy commented
## Travis tests have failed

Hey @someperson,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;transmission-remote-gui&#x2F;transgui&#x2F;jobs&#x2F;558382709">View build log</a>


<details>
  <summary>
    <strong>
     docker run -e DEBIAN_FRONTEND&#x3D;noninteractive -it --rm -v &quot;${PWD}:&#x2F;transgui&quot; -v &#x2F;usr&#x2F;bin&#x2F;qemu-arm-static:&#x2F;usr&#x2F;bin&#x2F;qemu-arm-static resin&#x2F;armv7hf-debian:stretch bash -c &quot;sed -i &#39;s&#x2F;archive.raspbian.org&#x2F;mirrors.ocf.berkeley.edu\&#x2F;raspbian&#x2F;g&#39; &#x2F;etc&#x2F;apt&#x2F;sources.list &amp;&amp; cd &#x2F;transgui&#x2F;setup&#x2F;unix&#x2F; &amp;&amp; .&#x2F;debian-ubuntu-install_deps.sh &amp;&amp; apt upgrade -y &amp;&amp; .&#x2F;build.sh&quot;
    </strong>
  </summary>

```
Unable to find image 'resin/armv7hf-debian:stretch' locally
stretch: Pulling from resin/armv7hf-debian


9c38b5a8a4d5: Pulling fs layer 


b6c38cb56e3d: Pulling fs layer 


a9ba470ed69f: Pulling fs layer 


9280f1f3d3ab: Pulling fs layer 


61315148afc1: Pulling fs layer 


63f18a2cd857: Pulling fs layer 


78ff8e9a6a0a: Pulling fs layer 


cec690eeedd1: Pulling fs layer 


b49d3d3847bd: Pulling fs layer 


7ce98b1e4f48: Pulling fs layer 


af4f02fb96a4: Pulling fs layer 


a35953622198: Pulling fs layer 


4b8a5ac42bf9: Pulling fs layer 


4859ee542ccc: Pulling fs layer 

9280f1f3d3ab: Waiting 

61315148afc1: Waiting 

63f18a2cd857: Waiting 

78ff8e9a6a0a: Waiting 

cec690eeedd1: Waiting 

b49d3d3847bd: Waiting 

7ce98b1e4f48: Waiting 

af4f02fb96a4: Waiting 

a35953622198: Waiting 

4b8a5ac42bf9: Waiting 

4859ee542ccc: Waiting 

b6c38cb56e3d: Downloading  18.24kB/1.787MB

a9ba470ed69f: Downloading  130.1kB/12.81MB

9c38b5a8a4d5: Downloading  195.7kB/19.29MB

b6c38cb56e3d: Download complete 

9c38b5a8a4d5: Downloading  10.12MB/19.29MB

a9ba470ed69f: Downloading  7.716MB/12.81MB

a9ba470ed69f: Verifying Checksum 

a9ba470ed69f: Download complete 

9c38b5a8a4d5: Verifying Checksum 

9c38b5a8a4d5: Download complete 

9c38b5a8a4d5: Extracting  196.6kB/19.29MB

9280f1f3d3ab: Downloading  5.919kB/473.6kB

9280f1f3d3ab: Verifying Checksum 

9280f1f3d3ab: Download complete 

9c38b5a8a4d5: Extracting  1.966MB/19.29MB

9c38b5a8a4d5: Extracting  3.539MB/19.29MB

61315148afc1: Downloading     486B/7.325kB

61315148afc1: Downloading  7.325kB/7.325kB

61315148afc1: Verifying Checksum 

61315148afc1: Download complete 

63f18a2cd857: Downloading     366B/366B

63f18a2cd857: Verifying Checksum 

63f18a2cd857: Download complete 

9c38b5a8a4d5: Extracting  5.505MB/19.29MB

78ff8e9a6a0a: Downloading     266B/266B

78ff8e9a6a0a: Verifying Checksum 

78ff8e9a6a0a: Download complete 

9c38b5a8a4d5: Extracting  7.078MB/19.29MB

9c38b5a8a4d5: Extracting  8.651MB/19.29MB

b49d3d3847bd: Downloading     190B/190B

b49d3d3847bd: Verifying Checksum 

b49d3d3847bd: Download complete 

cec690eeedd1: Downloading     255B/255B

cec690eeedd1: Verifying Checksum 

cec690eeedd1: Download complete 

9c38b5a8a4d5: Extracting  10.62MB/19.29MB

7ce98b1e4f48: Downloading  33.21kB/3.21MB

9c38b5a8a4d5: Extracting  12.19MB/19.29MB

7ce98b1e4f48: Downloading  3.185MB/3.21MB

7ce98b1e4f48: Verifying Checksum 

7ce98b1e4f48: Download complete 

9c38b5a8a4d5: Extracting  13.17MB/19.29MB

a35953622198: Downloading     489B/1.607kB

a35953622198: Downloading  1.607kB/1.607kB

a35953622198: Verifying Checksum 

a35953622198: Download complete 

af4f02fb96a4: Downloading     403B/403B

af4f02fb96a4: Verifying Checksum 

af4f02fb96a4: Download complete 

9c38b5a8a4d5: Extracting  15.73MB/19.29MB

9c38b5a8a4d5: Extracting  16.52MB/19.29MB

4b8a5ac42bf9: Downloading     350B/350B

4b8a5ac42bf9: Verifying Checksum 

4b8a5ac42bf9: Download complete 

4859ee542ccc: Downloading     249B/249B

4859ee542ccc: Verifying Checksum 

4859ee542ccc: Download complete 

9c38b5a8a4d5: Extracting  17.89MB/19.29MB

9c38b5a8a4d5: Extracting  18.28MB/19.29MB

9c38b5a8a4d5: Extracting  19.07MB/19.29MB

9c38b5a8a4d5: Extracting  19.29MB/19.29MB

9c38b5a8a4d5: Pull complete 

b6c38cb56e3d: Extracting  32.77kB/1.787MB

b6c38cb56e3d: Extracting   1.18MB/1.787MB

b6c38cb56e3d: Extracting  1.787MB/1.787MB

b6c38cb56e3d: Pull complete 

a9ba470ed69f: Extracting  131.1kB/12.81MB

a9ba470ed69f: Extracting  1.573MB/12.81MB

a9ba470ed69f: Extracting  3.277MB/12.81MB

a9ba470ed69f: Extracting  5.243MB/12.81MB

a9ba470ed69f: Extracting  7.864MB/12.81MB

a9ba470ed69f: Extracting  10.49MB/12.81MB

a9ba470ed69f: Extracting  12.19MB/12.81MB

a9ba470ed69f: Extracting  12.81MB/12.81MB

a9ba470ed69f: Pull complete 

9280f1f3d3ab: Extracting  32.77kB/473.6kB

9280f1f3d3ab: Extracting  473.6kB/473.6kB

9280f1f3d3ab: Extracting  473.6kB/473.6kB

9280f1f3d3ab: Pull complete 

61315148afc1: Extracting  7.325kB/7.325kB

61315148afc1: Extracting  7.325kB/7.325kB

61315148afc1: Pull complete 

63f18a2cd857: Extracting     366B/366B

63f18a2cd857: Extracting     366B/366B

63f18a2cd857: Pull complete 

78ff8e9a6a0a: Extracting     266B/266B

78ff8e9a6a0a: Extracting     266B/266B

78ff8e9a6a0a: Pull complete 

cec690eeedd1: Extracting     255B/255B

cec690eeedd1: Extracting     255B/255B

cec690eeedd1: Pull complete 

b49d3d3847bd: Extracting     190B/190B

b49d3d3847bd: Extracting     190B/190B

b49d3d3847bd: Pull complete 

7ce98b1e4f48: Extracting  32.77kB/3.21MB

7ce98b1e4f48: Extracting  1.212MB/3.21MB

7ce98b1e4f48: Extracting  2.916MB/3.21MB

7ce98b1e4f48: Extracting   3.21MB/3.21MB

7ce98b1e4f48: Pull complete 

af4f02fb96a4: Extracting     403B/403B

af4f02fb96a4: Extracting     403B/403B

af4f02fb96a4: Pull complete 

a35953622198: Extracting  1.607kB/1.607kB

a35953622198: Extracting  1.607kB/1.607kB

a35953622198: Pull complete 

4b8a5ac42bf9: Extracting     350B/350B

4b8a5ac42bf9: Extracting     350B/350B

4b8a5ac42bf9: Pull complete 

4859ee542ccc: Extracting     249B/249B

4859ee542ccc: Extracting     249B/249B

4859ee542ccc: Pull complete 
Digest: sha256:845bfccc8992389b8eaaf1d41c9a09205c12f405f42990c7c52d2e21e8f2194a
Status: Downloaded newer image for resin/armv7hf-debian:stretch
[WARN  tini (26)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
+ apt update -yqq
16 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ apt install -yqq lazarus xz-utils coreutils git make jq zip libssl-dev
coreutils is already the newest version (8.26-3).
coreutils set to manually installed.
The following additional packages will be installed:
  binutils dh-python fontconfig fontconfig-config fonts-dejavu-core
  fp-compiler fp-compiler-3.0.0 fp-units-base fp-units-base-3.0.0 fp-units-fcl
  fp-units-fcl-3.0.0 fp-units-gtk2 fp-units-gtk2-3.0.0 fp-units-rtl-3.0.0
  gir1.2-atk-1.0 gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0
  gir1.2-gtk-2.0 gir1.2-pango-1.0 git-man gnome-icon-theme
  gtk-update-icon-cache hicolor-icon-theme icu-devtools lazarus-1.6
  lazarus-doc-1.6 lazarus-ide lazarus-ide-1.6 lazarus-ide-gtk2-1.6
  lazarus-src-1.6 lcl-1.6 lcl-gtk2-1.6 lcl-nogui-1.6 lcl-units-1.6
  lcl-utils-1.6 libasan3 libatk1.0-0 libatk1.0-data libatk1.0-dev libatomic1
  libavahi-client3 libavahi-common-data libavahi-common3 libbsd0 libc-dev-bin
  libc6 libc6-dev libcairo-gobject2 libcairo-script-interpreter2 libcairo2
  libcairo2-dev libcroco3 libcups2 libcurl3-gnutls libdatrie1 libdbus-1-3
  libdpkg-perl liberror-perl libexpat1 libexpat1-dev libfontconfig1
  libfontconfig1-dev libfreetype6 libfreetype6-dev libgcc-6-dev libgdbm3
  libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgdk-pixbuf2.0-dev
  libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev libgom [...]

2019-07-14 01:13 UTC, someperson commented
@bertybassett Could you please retest using my latest build? It should run in macOS 10.15 Public Beta 2 (if you're still running Public Beta 1 or an older developer release, you might need to update).

2019-07-15 15:33 UTC, PeterDaveHello commented
Look like the issue was resolved from upstream, I don't have macOS v10.15 beta yet, so can't test it right now, but please feel free to let me know when it's ready to be merged! Thanks.

2019-07-15 16:19 UTC, someperson commented
@PeterDaveHello My concern with merging this in as things stand is that I haven't tested (and am not even sure I know how to test in some cases) all features in the application. I only discovered the other day that the "New connection" dialog was broken, for example, and it wasn't hard to fix, but I don't know if there are more instances like this. This is why I have been calling my builds alpha versions.

I have confirmed that the application runs in my 10.15 VM, but 10.15 isn't required to test it. I don't know how far back it supports, but it definitely runs in 10.14, and Travis CI compiles it in a 10.13 environment, so I'd expect it to work there as well.

2019-07-15 16:33 UTC, PeterDaveHello commented
@someperson yes, we should test it more 😙

2019-07-15 16:34 UTC, PeterDaveHello commented
@someperson btw, may I know your development environment? Is it also macOS v10.14? Thanks

2019-07-15 16:54 UTC, PeterDaveHello commented
I try to run this PR on a macOS 10.14 but this line `lazbuild --build-ide= --compiler=ppcx64 --cpu=x86_64 --widgetset=cocoa` got error, still working on a solution.

```
SetupCompilerFilename: The compiler path "ppcx64" => "" is invalid (Error: file not found) Searching a proper one ...
SearchCompilerCandidates Value=ppcx64 File=
SearchCompilerCandidates Value=/usr/local/bin/ppc386 File=/usr/local/bin/ppc386
SearchCompilerCandidates Value=/usr/local/bin/ppc386 File=/usr/local/bin/ppc386
SearchCompilerCandidates Value=fpc File=
SearchCompilerCandidates Value=ppc386 File=
SearchCompilerCandidates Value=/usr/local/bin/ppc386 File=/usr/local/bin/ppc386
SearchCompilerCandidates Value=/usr/bin/ppc386 File=/usr/bin/ppc386
SearchCompilerCandidates Value=/opt/fpc/ppc386 File=/opt/fpc/ppc386
SearchCompilerCandidates Value=$(LazarusDir)/fpc/3.0.4/bin/i386-darwin/fpc File=/Developer/lazarus/fpc/3.0.4/bin/i386-darwin/fpc
SearchCompilerCandidates Value=$(LazarusDir)/fpc/bin/i386-darwin/fpc File=/Developer/lazarus/fpc/bin/i386-darwin/fpc
SearchCompilerCandidates Value=/usr/local/bin/fpc File=/usr/local/bin/fpc
SearchCompilerCandidates Value=/usr/bin/fpc File=/usr/bin/fpc
SearchCompilerCandidates Value=/opt/fpc/fpc File=/opt/fpc/fpc
SetupCompilerFilename: no proper compiler found.
Warning: (lazarus) [TBuildManager.RescanCompilerDefines]: invalid compiler:
Environment compiler: "": missing file name


  $0009EF5B
  $0009B17E
  $00011B66
  $005077F7
  $0018BCD4
  $00194B5E
  $00194EDE
  $0001292A
  $00016D0E
Error: (lazbuild) Error
There is no Free Pascal Compiler (e.g. fpc or ppc<cpu>) configured in the environment options. Codetools will not work properly.
Environment compiler: "": missing file name
lazbuild is non interactive, aborting now.
```

2019-07-15 17:11 UTC, PeterDaveHello commented
I'm asking this because I can't install fpc v3.0.4 on macOS v10.14, but v3.0.4a can :thinking: maybe need to upgrade fpc here.

```
$ sudo installer -pkg /Volumes/fpc-3.0.4.intel-macosx/fpc-3.0.4.intel-macosx.pkg -target /
installer: Cannot install on volume / because it is disabled.
installer: You have to install Xcode and its command line tools before installing this package. See http://www.freepascal.org/down/i386/macosx-netherlands.var for information on how to install the command line tools.
```

```
 $ sudo installer -pkg /Volumes/fpc-3.0.4a.intel-macosx/fpc-3.0.4a.intel-macosx.pkg -target /
installer: Package name is Free Pascal Compiler Intel 3.0.4
installer: Upgrading at base path /
installer: The upgrade was successful.
```

2019-07-15 17:22 UTC, someperson commented
@PeterDaveHello My development environment is 10.14, though admittedly, I installed FPC and Lazarus on it manually, rather than using the script. I tried bumping FPC to 3.0.4a the other day, but for reasons I didn't understand, this resulted in problems compiling it in Travis CI, whereas 3.0.4 worked. If you want, I can look more into this.

2019-07-15 17:35 UTC, someperson commented
@PeterDaveHello Something also worth noting is that I've noticed that the builds I've produced on my machine in 10.14 are Dark Mode-aware, but Lazarus' support for Dark Mode seems to be incomplete, resulting in some UI elements being unreadable if the user has Dark Mode enabled. The builds from Travis CI don't have this issue since the application produced runs solely in Light Mode regardless of the user's settings. Do we need to find a workaround for this now?

2019-07-15 18:31 UTC, PeterDaveHello commented
@someperson feel free to help improve any part of this project, including dependency upgrade like macOS, fpc, lazarus, etc, and also features like the dark mode.

I'm still trying to understand why I'm facing the issues on macOS 10.14, already tried on both model of 2014 and 2018, thanks for your help anyway!

2019-08-10 10:52 UTC, FezVrasta commented
I tried to compile this branch but it still outputs a 32bit executable on Catalina... 
```
sh -c 'cd setup/macosx && ./compilers.sh'
sh -c 'cd setup/macosx && ./create_app_new.sh' 
```

am I missing something?

2019-08-24 16:21 UTC, jeromeof commented
I am on the latest Catalina Beta - any chance of a DMG file so I can test it also?

2019-08-26 21:57 UTC, jeromeof commented
> I just turned on Issues in my repo, so feel free to file anything specific to the 64-bit builds there. Thanks for the heads-up; I didn't even know Issues could be turned off.

Thanks, briefly installed it and it works fine - once I got past the security 'integrity' warning apple display. I will try and test it more fully in the next few days but it looks great.

2019-08-29 00:54 UTC, someperson commented
@PeterDaveHello I just merged in a number of improvements, including fixes for building on macOS 10.14. I also bumped the Travis CI environment to Xcode 10.3 on macOS 10.14. Would you mind retesting with these changes?

2019-08-29 01:11 UTC, PeterDaveHello commented
@someperson Sure, I will take a look soon, thanks!

2019-08-29 01:11 UTC, PeterDaveHello commented
@PeterDaveHello Sure, I will take a look soon, thanks!

2019-08-29 01:38 UTC, PeterDaveHello commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
I'm not sure but wondering if this one should be separated into another commit as it affects not only macOS build?

2019-08-29 18:47 UTC, PeterDaveHello commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
Do you think it's possible to separate it into another PR which should be merged before this one? I think we can do some tests to make sure it won't bring some negative affects to the current builds. Thanks.

2019-08-29 20:01 UTC, someperson commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
I can definitely put it on a branch by itself and create a PR for it. I'll go ahead and do that. Thanks!

2019-09-08 14:56 UTC, PeterDaveHello commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
Thanks!

2019-09-08 14:59 UTC, PeterDaveHello commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
I've merged #1252 , so let's remove this diff here?

2019-09-08 18:54 UTC, someperson commented on transgui.lpi
> +      <CustomOptions Value="-Sa -CX -XX"/>
Done.

2019-09-13 14:47 UTC, PeterDaveHello approved these changes

2019-09-13 14:47 UTC, merged

2019-09-16 00:33 UTC, srscott commented
Just downloaded transgui-5.17.0-cocoa-alpha6 on latest Catalina beta (19A558d) and so far all is fine.
Thank you so much for this 64bit build @someperson

2019-10-06 18:04 UTC, durosity commented
Just FYI on Catalina 19A582a I've found that the file listings display peculiarly when dark mode is enabled.  see screenshot for details
![Screenshot 2019-10-06 at 19 02 36](https://user-images.githubusercontent.com/17961550/66273459-1cdf0280-e86c-11e9-97c9-cd52704ce632.png)

2019-10-21 23:45 UTC, garz75 commented
Thank you so much @someperson for porting to 64bits and Cocoa, and thanks @PeterDaveHello for the quick merge. I had the build from Sam installed for two weeks, had no issue with it even after the upgrade to Catalina, and I just upgraded to the new 5.18.0 official version, no problem either so far.

2024-12-03 18:50 UTC, VPurselley commented
Is this still active?