Update README.md
transmission-remote-gui/transgui pull request #1433
Opened 2022-11-24 19:33 UTC by myxomatosis

Add step in install instructions to build transgui.res file

2023-03-09 14:02 UTC, PeterDaveHello requested changes
Changes on 11468327a01e9f834e49748c717c3c48450d57e2 should be removed, right?

2023-03-09 14:02 UTC, PeterDaveHello commented on rpc.pas
> -      Http.MimeType:='application/json';
This is not related, is it?

2023-03-11 05:25 UTC, myxomatosis commented on rpc.pas
> -      Http.MimeType:='application/json';
No, sorry about that. I have reverted that commit.

2023-03-12 12:07 UTC, PeterDaveHello approved these changes

2023-03-12 12:07 UTC, merged